# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions
# More info on Python, GitHub Actions, and Azure App Service: https://aka.ms/python-webapps-actions

name: Build and deploy Python app to Azure Web App - app-dev-baker-246

on:
  push:
    branches:
      - main

permissions:
  id-token: write 
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      ACR_NAME: ${{ secrets.PERSONAL_WEBSITE_ACR_NAME }}
      IMAGE_NAME: ${{ secrets.PERSONAL_WEBSITE_IMAGE_NAME }}
      IMAGE_TAG: v1.${{ github.sha }}
      WEBAPP_NAME: ${{ secrets.PERSONAL_WEBSITE_WEBAPP_NAME }}
      RESOURCE_GROUP: ${{ secrets.PERSONAL_WEBSITE_RG }}
      IMAGE: "${{ secrets.PERSONAL_WEBSITE_IMAGE_NAME }}:v1.${{ github.sha }}"
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4          
        
      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_GITHUB_OIDC }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
            
      - name: Build and push image
        run: |
          az acr login --name $ACR_NAME
          IMAGE="$ACR_NAME.azurecr.io/$IMAGE"
          docker build -t $IMAGE .
          docker push $IMAGE
            
      - name: Deploy Web App container
        run: |
          IMAGE="${{ env.ACR_NAME }}.azurecr.io/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}"

          az webapp config container set \
            --name ${{ env.WEBAPP_NAME }} \
            --resource-group ${{ env.RESOURCE_GROUP }} \
            --container-image-name $IMAGE

      - name: Restart Web App
        run: |
          az webapp restart \
            --name ${{ env.WEBAPP_NAME }} \
            --resource-group $}{{ env.RESOURCE_GROUP }}        
